platform :ios, '15.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_modular_headers!  # ✅ ВАЖНО (фикс твоей ошибки)

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      min_ios = '15.0'
      current = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']

      if current.nil? || Gem::Version.new(current) < Gem::Version.new(min_ios)
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = min_ios
      end

      # permissions
      gcc = config.build_settings['GCC_PREPROCESSOR_DEFINITIONS']
      gcc = ['$(inherited)'] if gcc.nil?
      gcc = [gcc] unless gcc.is_a?(Array)

      %w[
        PERMISSION_CAMERA=1
        PERMISSION_MICROPHONE=1
        PERMISSION_PHOTOS=1
      ].each do |flag|
        gcc << flag unless gcc.include?(flag)
      end

      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = gcc
    end

    # fix geocoding_ios bug
    if target.name == 'geocoding_ios'
      target.source_build_phase.files.to_a.each do |build_file|
        path = build_file.file_ref&.path.to_s
        build_file.remove_from_project if path.end_with?('PrivacyInfo.xcprivacy')
      end
    end
  end

  installer.aggregate_targets.each do |aggregate_target|
    aggregate_target.xcconfigs.each do |_, config_file|
      config_file.attributes['LIBRARY_SEARCH_PATHS'] =
        '$(inherited) "${PODS_CONFIGURATION_BUILD_DIR}" ' +
        (config_file.attributes['LIBRARY_SEARCH_PATHS'] || '')
    end
  end
end
